CREATE TABLE IF NOT EXISTS tb_produto
(
    id                 bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    codigo_de_barras   bigint,
    codigo_produto     varchar(8) NOT NULL,
    serie              varchar(8),
    nome               varchar(40),
    descricao          varchar(100),
    categoria          varchar(30),
    valor_bruto        numeric(19, 2),
    impostos           numeric(19, 2),
    data_de_fabricacao date,
    data_de_validade   date,
    cor                varchar(30),
    material           varchar(30),
    quantidade         integer,
    valor_final        numeric(19, 2),
    CONSTRAINT tb_produto_codigo_produto_key UNIQUE (codigo_produto),
    CONSTRAINT tb_produto_pkey PRIMARY KEY (id)
);