version: '3.1'

services:

  API:
    container_name: produto_api
    build:
      context: ./
    image: produto/api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - URL_POSTGRES=jdbc:postgresql://PostgreSQL:5432/produto_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=12345678
    depends_on:
      - rabbitmq
      - PostgreSQL
    networks:
      - produto-api-network

  PostgreSQL:
    container_name: postgres_db
    image: postgres:12-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=produto_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    networks:
      - produto-api-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - produto-api-network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=12345678
networks:
  produto-api-network: